const fs = require('fs');
let content = fs.readFileSync('src/UserManagement.jsx', 'utf8');
content = content.replace('<table className="w-full text-left whitespace-nowrap">', '<table className="w-full text-left table-fixed">');
content = content.replace('<th className="p-4 pl-6 w-10 text-center">', '<th className="p-4 pl-6 w-12 text-center">');
content = content.replace('<th className="p-4 w-10 text-center">No</th>', '<th className="p-4 w-12 text-center">No</th>');
content = content.replace('<th className="p-4">사용자명</th>', '<th className="p-4 w-[11%]">사용자명</th>');
content = content.replace('<th className="p-4">사용자 ID</th>', '<th className="p-4 w-[12%]">사용자 ID</th>');
content = content.replace('<th className="p-4">소속 팀</th>', '<th className="p-4 w-[11%]">소속 팀</th>');
content = content.replace('<th className="p-4">소속 브랜드</th>', '<th className="p-4 w-[13%]">소속 브랜드</th>');
content = content.replace('<th className="p-4">담당 업체/창고</th>', '<th className="p-4 w-[15%]">담당 업체/창고</th>');
content = content.replace('<th className="p-4">권한 그룹</th>', '<th className="p-4 w-[8%]">권한 그룹</th>');
content = content.replace('<th className="p-4 text-center">가입일시</th>', '<th className="p-4 w-[12%] text-center">가입일시</th>');
content = content.replace('<th className="p-4 text-center">상태</th>', '<th className="p-4 w-[6%] text-center">상태</th>');
content = content.replace('<td className="p-4 font-black text-gray-800 text-sm tracking-tight">{user.name}</td>', '<td className="p-4 font-black text-gray-800 text-sm tracking-tight truncate" title={user.name}>{user.name}</td>');
content = content.replace('<td className="p-4 font-bold text-gray-600">{user.login_id}</td>', '<td className="p-4 font-bold text-gray-600 truncate" title={user.login_id}>{user.login_id}</td>');
content = content.replace('<td className="p-4 text-gray-600 font-medium">{user.team || \\'-\\'}</td>', '<td className="p-4 text-gray-600 font-medium truncate" title={user.team || \\'-\\'}>{user.team || \\'-\\'}</td>');
content = content.replace(/(<td className="p-4">\\s*<div className="flex gap-1.5 flex-wrap )max-w-\\[200px\\]/, '\\');
fs.writeFileSync('src/UserManagement.jsx', content);
console.log('done');
